var mongoose = require('mongoose');
var assert = require('assert');
var bluebird = require('bluebird');
// var db = require('../index.js');

var categorySchema = new mongoose.Schema({
  name: String,
  description: String,
  mottoes: [String],
  beliefs: [String]
});

var Category = mongoose.model('Category', categorySchema);

var data = [
  {
    "name":"Faith",
    "description": "Trust and confidence in a person or an idea.",
    "mottoes":[
      "Faith. Hope. Never quit."
    ],
    "beliefs":[
      "Pray every morning.",
      "That which does not kill us only makes us stronger.",
      "Believe in yourself.",
      "Faith is taking the first step even when you don't see the stairs.",
      "If God brings you to it, He will bring you through it.",
      "Understand to achieve anything requires faith in yourself, hard work and determination.",
      "All things are possible to those who believe.",
      "Be faithful in small things because it is in them that your strength lies.",
      "Have faith in your abilities.",
      "I move not without Thy knowledge!",
      "Make love a priority in all your decisions.",
      "The world turns aside to let any man pass who knows where he is going.",
      "In great difficulty, you will argue with yourself that there is no way forward. But with God, nothing is impossible.",
      "Attach yourself to what is spiritually superior, regardless of what other people think or do.",
      "Fasting brings you closer to God.",
      "Let your Faith be bigger than your fears."
    ]
  },
  {
    "name":"Hope",
    "description": "Expectation and desire for a positive outcome.",
    "mottoes":[
      "Hope. Faith. Never quit.",
      "Strength  Wisdom  Courage"
    ],
    "beliefs":[
      "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
      "Learn from yesterday. Live for today. Hope for tomorrow.",
      "There must be darkness for dawn to come.",
      "Be willing to give up what you are to become what you will be.",
      "Out of suffering emerge the strongest of souls.",
      "Find the light, faint though it may be, and never, ever stop moving toward it.",
      "The future is not some place we are going but one we are creating.",
      "The greater the difficulty, the more glory in surmounting it.",
      "It's not what happens to you, but how you react to it that matters.",
      "The pain you've been feeling can't compare to the joy that's coming.",
      "The past cannot be changed. The future is within your power.",
      "The future is filled with unknowable wonder.",
      "The best way to predict the future is to create it.",
      "The future is as bright as your faith,",
      "It is not in the stars to hold our destiny but in ourselves.",
      "Tomorrow is an unknowable canvas. You wield the brush.",
      "It is difficulties that show what men are.",
      "Practice mindfulness and perform acts of kindness everyday.",
      "You are stronger than whatever you are facing now.",
      "In times of adversity, just keep moving forward.",
      "We are here to laugh at the odds and live our lives so well that death will tremble to take us.",
      "Every adversity, failure and heartache carries with it the seed of an equal or greater benefit.",
      "You are neither your thoughts nor your emotions. Only the weak are subject to them.",
      "Above all, face your fear.",
      "The pain of today is the strength of tomorrow.",
      "Skillful pilots gain their reputation from storms and tempests.",
      "Do not let what you cannot do interfere with what you can do.",
      "Keep your face always toward the sunshine -- and shadows will fall behind you.",
      "Dismiss what insults your soul and your very flesh shall be a great poem.",
      "You must travel it by yourself. It is not far. It is within reach.",
      "In the middle of difficulty lies opportunity."
    ]
  },
  {
    "name":"Empathy",
    "description": "The ability to understand and share the feelings of others.",
    "mottoes":[
      "Kindness Matters"
    ],
    "beliefs":[
      "Always be kind",
      "Be kind. Everyone you meet is fighting a battle.",
      "Forgiveness is the attribute of the strong.",
      "See people from where they stand, not from where you stand.",
      "A word of encouragement during a failure is worth more than an hour of praise.",
      "Practice mindfulness and perform acts of kindness everyday.",
      "There is something to be learned from everyone.",
      "Everyone you meet is either a blessing or a lesson.",
      "Take nothing personally. Nothing others do is because of you.",
      "Before you speak, answer these: Is it true? Is it necessary? Is it kind?",
      "Be kind. Impose your will forcefully upon those who are not.",
      "One kind word can warm three winter months.",
      "Life isn't work living, unless it is lived for someone else.",
      "Preparation is the key to remaining calm under pressure.",
      "If someone loves you and hurts you, chances are they're in pain.",
      "Find joy in the accomplishments of others.",
      "Do unto others as you would have them do unto you.",
      "You are neither your thoughts nor your emotions. Only the sad are slaves to them.",
      "Make love a priority in all your decisions.",
      "Apologize when you've wronged. Do not withhold forgiveness.",
      "Listening is the beginning of understanding.",
      "Consider the rights of others before your own feelings.",
      "People are flawed. So are you. Forgive them.",
      "Everyone has at least one thing interesting about them. Find it.",
      "Any person capable of angering you becomes your master.",
      "Consider the feelings of others.",
      "It's not what happens to you, but how you react to it that matters.",
      "It's easy to see the splinter in someone else's eye and miss the log in your own.",
      "Be curious, not judgmental.",
      "I do not ask the wounded person how he feels, I myself become the wounded person.",
      "Treat others as you would treat yourself.",
      "When someone is feeling down, paint for them a compelling future.",
      "Compliment others.",
      "Ask yourself how you would feel in their shoes.",
      "Whoever sees himself as the judge of Truth and Knowledge will be shipwrecked by the laughter of the gods."
    ]
  },
  {
    "name":"Diligence",
    "description": "Hard work and persistence in achieving a goal.",
    "mottoes":[
      "Diligence  Resilience  Integrity",
      "Excellence Through Effort",
      "Choose To Strive",
      "Always Moving Forward"
    ],
    "beliefs":[
      "Feeling bad? WORK yourself better.",
      "Be quick, but don't hurry.",
      "Adjust or accept. Do not whine.",
      "Every night before bed, write down three goals for tomorrow.",
      "Write down each goal, tell it to friends and loved ones, then make it happen.",
      "Keep your hands out of your pockets. There is always something to do.",
      "Wake an hour earlier than everyone else to pray, learn and exercise.",
      "Tame your pain.",
      "Do what you can, with what you have, where you are.",
      "He that is good at making excuses is seldom good at anything else.",
      "Working through fatigue strengthens the soul.",
      "A day without Goals is a day without water for the soul.",
      "Procrastination, excuses and complaints are for lesser souls.",
      "Let your name be known as synonymous with Diligence.",
      "Once in mind a goal is made, the Finished Path is always stayed.",
      "Find or create value then do it better than everyone else.",
      "Download wisdom from mistakes then delete them from memory.",
      "Visualize accomplishment then anticipate and strategize probable challenges.",
      "The only way through suffering is straight through it.",
      "Strive for excellence in everything you do.",
      "You may delay, but time will not.",
      "Early to bed and early to rise makes a man healthy, wealthy and wise.",
      "A man who dares to waste one hour of time has not discovered the value of life.",
      "Whining and excuses are for lesser souls.",
      "The world owes you nothing. Earn everything.",
      "Do not let what you cannot do interfere with what you can do.",
      "Excuses are for lesser souls.",
      "What matters in life are results. No one cares about your excuses.",
      "Full effort is full victory.",
      "Make your bed first thing every morning.",
      "If you don't have time to do it right, when will you have time to do it over?",
      "The world belongs to the energetic.",
      "There are no shortcuts to anyplace worth going.",
      "Fill the unforgiving minute with sixty seconds of distance running.",
      "Hard work can help you accomplish anything.",
      "Wake up two hours early to read, work or learn something new.",
      "Pain is weakness leaving the body.",
      "Hard Work brings love and acceptance.",
      "Good things come to those who work hard and never give up.",
      "Always make a total effort, even when the odds are against you.",
      "Nothing of real value comes easily.",
      "Luck is real. The harder you work, the more you have.",
      "Without labor, nothing prospers.",
      "Want something? No shortcuts. Earn it."
    ]
  },
  {
    "name":"Perseverance",
    "description": "Moving forward toward a goal despite difficulty or delay.",
    "mottoes":[
      "Hope. Faith. Never quit.",
      "Decide. Commit. Succeed.",
      "Integrity  Honor  Courage.",
      "Strength  Endurance  Triumph",
      "Embracing Challenge",
      "Strength  Wisdom  Courage"
    ],
    "beliefs":[
      "Never, ever quit",
      "Fear brings more pain than the pain it fears.",
      "Never give up, no matter how impossible the situation looks. That's how legends are born.",
      "It's at the borders of pain and suffering that men are separated from boys.",
      "Souls are awakened out of suffering. The greatest souls endure many scars.",
      "Strength and growth come only through continuous effort and struggle.",
      "Above all, face your fear.",
      "You either win or you learn. The only way you can lose is by quitting.",
      "The pain of today is the strength of tomorrow.",
      "Out of suffering emerge the strongest souls. The most massive characters are seared with scars.",
      "Working through fatigue strengthens the soul.",
      "Working through fatigue brings us closer to God.",
      "Adjust or accept. Do not whine.",
      "No matter how you feel, get up, show up and never give up.",
      "Every adversity, failure and heartache carries with it the seed of an equal or greater benefit.",
      "Embody grit and toughness.",
      "Let your name be known as synonymous with Perseverance.",
      "You are neither your thoughts nor your emotions. Only the weak are subject to them.",
      "Wear failed attempts as badges of honor.",
      "Seek and embrace challenge - it forges your mettle.",
      "Seek and embrace challenge - it is the most certain path to strength.",
      "Vanquish your subservience to pain.",
      "Strength = Pain Endured",
      "Pain is inevitable. Suffering is optional.",
      "Nothing worth having ever comes easily.",
      "Pain is a divine rite of passage through which you are reborn as a being of strength and purpose.",
      "Endure and persist and the world will open itself to you.",
      "Hold true to your aspirations no matter what is going on around you.",
      "Excuses are for lesser souls.",
      "Poor is the man who is a slave to pain.",
      "Quitting is for lesser souls.",
      "Embrace the pain. Enjoy the gain.",
      "Skillful pilots gain their reputation from storms and tempests.",
      "The greater the difficulty, the more glory in surmounting it.",
      "It's not what happens to you, but how you react to it that matters.",
      "Failure is not fatal, but failure to change might be.",
      "Courage and perseverance are magical talismen, before which difficulties and obstacles crumble.",
      "Failing and losing aren't the same. Quitting is losing. Failing brings you closer to your goal.",
      "There are no dumb questions. Only dumb people that don't ask them.",
      "Failure brings you one step closer to your goal.",
      "Work. Fail. Repeat.",
      "There are no mistakes in service of a goal. There are only lessons learned.",
      "Never make excuses.",
      "In the middle of difficulty lies opportunity.",
      "Failure brings you one step closer to your goal.",
      "Work. Fail. Repeat.",
      "Pain is weakness leaving the body."
    ]
  },
  {
    "name":"Prudence",
    "description": "Using wisdom and good judgement in decisions.",
    "mottoes":[
      "Strength  Wisdom  Courage"
    ],
    "beliefs":[
      "Invest one-fourth of everything you earn.",
      "The doorstep to the Temple of Wisdom is knowledge of our own ignorance.",
      "Not our thoughts or emotions. It is our actions that define us.",
      "We are responsible for what we do no matter how we feel.",
      "Priorities: Physically fit, emotionally stable and spiritually sound.",
      "Spend less than you earn. Invest the rest.",
      "Adjust or accept. Do not whine.",
      "Truth alone will endure. All the rest will be swept away before the tide of time.",
      "If you wish to know a man, ignore his words and observe his actions.",
      "Only idiots make the same mistake twice.",
      "The only true wisdom is in knowing you know nothing.",
      "Think before you act. Something done in an instant can give you heartache for life.",
      "Evaluate what you want to say. Then and only then, speak.",
      "Change what you can, accept what you can't and remove yourself from the unacceptable.",
      "In times of pleasurable temptation, focus your thoughts on a different pleasure.",
      "Let your word become known as unimpeachable.",
      "Fix Reason firmly in her seat and call to her tribunal every fact, every opinion.",
      "He that is good at making excuses is seldom good at anything else.",
      "Poor is the man who is slave to his emotions.",
      "Inside each of us are two wolves: Good and Bad. Which one wins? The one you feed.",
      "Take nothing personally. Nothing others do is because of you.",
      "Do what you say you will do.",
      "Worrying is as effective as trying to solve an algebra problem by chewing bubble gum.",
      "If you are patient in one moment of anger, you will escape a hundred days of sorrow.",
      "Visualize accomplishment then anticipate and strategize probable challenges.",
      "For there is nothing good or bad, but thinking makes it so.",
      "Let your name be known as synonymous with Integrity.",
      "Do unto others as you would have them do unto you.",
      "You are neither your thoughts nor your emotions. Only the weak are subject to them.",
      "Know your exact net worth at all times.",
      "Above all, face your fear.",
      "Weakness of attitude becomes weakness of character.",
      "Preparation is the key to remaining calm under pressure.",
      "In all matters of money, take nothing personally but remain vigilant - all are self-interested.",
      "Always be open to new information.",
      "Do not deny your emotions - master them.",
      "Download lessons from mistakes then delete the mistake from memory.",
      "Don't let yourself be controlled by people, money or past experiences.",
      "Seek feedback and be open to criticism. They are the paths to excellence.",
      "Control thy passions lest they take vengeance on thee.",
      "Any person capable of angering you becomes your master.",
      "It is the act of an ill-constructed man to blame others for his own bad condition.",
      "Success is never final; failure is never fatal. It's courage that counts.",
      "If you don't have time to do it right, when will you have time to do it over?",
      "Trust your gut to point in the right direction. Then use logic and reason to make the decision.",
      "Keep a ledger.",
      "Apologize when you've wronged. Do not withhold forgiveness.",
      "Choose your words wisely, embrace every moment and never waste time.",
      "Strive for excellence in everything you do.",
      "Attend to nothing except reason in everything you encounter.",
      "Attach yourself to what is spiritually superior, regardless of what other people think or do.",
      "It's not what happens to you, but how you react to it that matters.",
      "Never make excuses.",
      "First learn the meaning of what you will say. Then speak.",
      "Exercise and practice mindfulness daily.",
      "Do not let what you cannot do interfere with what you can do.",
      "Always pay yourself first by investing one-fourth of your earnings before doing anything else.",
      "Never spend on the unnecessary what you haven't already earned."
    ]
  },
  {
    "name":"Temperance",
    "description":"The ability to delay gratification.",
    "mottoes":[
      "Hope. Faith. Never quit."
    ],
    "beliefs":[
      "In times of temptation, reflect on what you're grateful for.",
      "Do something everyday that scares you.",
      "Out of suffering emerge the strongest souls. The most massive characters are seared with scars.",
      "The pain of today is the strength of tomorrow.",
      "Preparation is the key to remaining calm under pressure.",
      "Mindfulness meditation is exercise for the mind. Do it every day.",
      "Exercise and practice mindfulness every day.",
      "You are neither your thoughts nor your emotions. Only the weak are subject to them.",
      "No man is free who is not a master of himself.",
      "Capitulation is for lesser souls.",
      "He who angers you conquers you.",
      "Poor is the man ruled by his emotions.",
      "For there is nothing good or bad, but thinking makes it so.",
      "Make your bed first thing every day.",
      "Do not judge the day by the harvest you reap but by the seeds you plant.",
      "Make whatever you think best a law you never set aside.",
      "Remain vigilant: Your progress can be wrecked or preserved by a single day and a single event.",
      "Resolve to live as a grown-up, and make whatever you think best a law you never set aside.",
      "You are not your thoughts. You are not your emotions. Become their master.",
      "Decisions against our betters selves offend the soul.",
      "Attach yourself to what is spiritually superior, regardless of what other people think or do.",
      "Begin everyday by counting your blessings.",
      "It's not what happens to you, but how you react to it that matters.",
      "When faced with temptation, occupy yourself with prayer, a wholesome pleasure or work.",
      "Fiercely guard your environment against temptation.",
      "Forgive yourself, make corrections, redouble your efforts and move forward."
    ]
  },
  {
    "name":"Happiness",
    "description": "Helping others, having close relationships and doing something productive you enjoy.",
    "mottoes":[
      "Enjoying Every Moment",
      "Veni  Vidi  Amavi"
    ],
    "beliefs":[
      "Only fools worry about things beyond their control.",
      "Be yourself. Everyone else is already taken.",
      "Try something new. Enjoy the fun of failure.",
      "Wherever you are, be there totally.",
      "Make your needs known.",
      "Never outgrow play.",
      "Happiness is when what you think, what you say and what you do are in harmony.",
      "Enjoy it while it's here. Let go when it leaves.",
      "Our biggest regrets are often opportunities we miss because of fear.",
      "Download wisdom from mistakes then delete them from memory.",
      "Let insults roll off your back like water rolls off feathers.",
      "Adjust or accept. Do not whine.",
      "Worrying is as effective as trying to solve an algebra problem by chewing bubble gum.",
      "Practice mindfulness and perform acts of kindness everyday.",
      "Find joy in the accomplishments of others.",
      "For there is nothing good or bad, but thinking makes it so.",
      "Do unto others as you would have them do unto you.",
      "You are neither your thoughts nor your emotions. Do not be ruled by them.",
      "Apologize when you've wronged. Do not withhold forgiveness.",
      "Be true to yourself.",
      "Embrace change.",
      "Procrastination, excuses and complaints are for lesser souls.",
      "Consider your mortality.",
      "This day, like any day, could be your last. It's easy to forget that. So don't.",
      "Don't take yourself too seriously. Life is more farce than drama.",
      "We are here to laugh at the odds and live our lives so well that death will tremble to take us.",
      "Make love a priority in all your decisions.",
      "Covet not many things and you will obtain.",
      "Any person capable of angering you becomes your master.",
      "He who laughs at himself never runs out of things to laugh at.",
      "Don't seek to have events happen as you wish, but wish them to happen as they do.",
      "Begin everyday by counting your blessings.",
      "Find three hobbies you love: One to make money, one to stay in shape and one to be creative.",
      "Don't let yourself be controlled by people, money or past experiences.",
      "Seek not the good in external things; seek it in yourself.",
      "Wealth consists not in having great possessions, but in having few wants.",
      "Live so that your happiness depends as little as possible upon external things.",
      "First say to yourself what you would be. Then do what you have to do.",
      "For your closest friends, work hard to bridge the gaps in geography and lifestyle.",
      "Cease worrying about things which are beyond the power of our will.",
      "Do not let what you cannot do interfere with what you can do.",
      "You miss 100% of the shots you don't take.",
      "Above all, face your fears.",
      "Have the heart of a lion, the skin of a rhino and the soul of an angel.",
      "Find someone to love, something to do and something to hope for.",
      "Choose your words wisely, embrace every moment and never waste time.",
      "It's better to be a failure at something you love than a success at something you hate.",
      "The greatest mistake you can make in life is to continually be afraid you will make one.",
      "Pick one and become excellent: Dance, sing or play an instrument.",
      "The wise do not grieve for which they have not, but rejoices for what they have.",
      "It's not what happens to you, but how you react to it that matters.",
      "At least in part, accept responsibility for everything that happens to you.",
      "Keep company with only those that uplift you, whose presence calls forth your best."

    ]
  },
  {
    "name":"Creativity",
    "description":"The ability to generate original ideas.",
    "mottoes":[
      "Different is Magnificent"
    ],
    "beliefs":[
      "Logic will get you from A to B. Imagination will take you Anywhere.",
      "To live a creative life we must lose our fear of being wrong.",
      "Creativity is just connecting things.",
      "Question everything you hear and see.",
      "Embrace change.",
      "Do something everyday that scares you.",
      "Trust your instincts.",
      "At least once a day, allow yourself to think and dream in solitude.",
      "Creating something new is accomplished not by the intellect but by the play instinct.",
      "Spend more time thinking about the problem than thinking up solutions.",
      "Download wisdom from mistakes then delete them from memory.",
      "Be true to yourself.",
      "Trust your gut, value fantasy, be open to new experiences and play with problems.",
      "Wear failed attempts as badges of honor.",
      "Anyone who has never made a mistake has never tried anything new.",
      "This is not a sentence.",
      "Let insults roll off your back like water off feathers.",
      "The important thing is to not stop questioning.",
      "Above all, face your fears.",
      "Out of clutter, find simplicity.",
      "Never outgrow play.",
      "No one is remembered for being normal.",
      "If you cannot find a way, make one.",
      "Only those who attempt the absurd achieve the impossible.",
      "The most beautiful experience we can have is the mysterious.",
      "Don't take yourself too seriously.",
      "Consider your mortality.",
      "Seek feedback and be open to criticism. They are guideposts to improvement.",
      "Not doing something out of fear of looking stupid is more stupid than anything you can possibly do.",
      "Do not let what you cannot do interfere with what you can do.",
      "You miss 100% of the shots you don't take.",
      "The greatest mistake you can make in life is to continually be afraid you will make one.",
      "Creativity is intelligence having fun.",
      "Life is a great big canvas. Throw all the paint you can on it.",
      "Some see things and ask why. Dream things that never were and ask 'Why not?'",
      "It's good to remember and easy to forget: You don't have to do what everyone else is doing.",
      "Revel in your difference.",
      "Almost anything is possible.",
      "If you're going to fail, fail with 100% effort.",
      "Life is absurd. Be comfortable with appearing foolish.",
      "Sometimes it's wonderful to be silly.",
      "Make mistakes, look like an idiot, then try again - without flinching.",
      "Try something new. Enjoy the fun of failure.",
      "Different is Magnificent.",
      "Each day is a gift. Honor yourself and your family by never taking it for granted.",
      "Observe the human comedy.",
      "Be yourself. Everyone else is already taken.",
      "Stay hungry. Stay foolish."
    ]
  },
  {
    "name":"Learning",
    "description":"Gaining knowledge or skills.",
    "mottoes":[
      "Always Learning"
    ],
    "beliefs":[
      "Always be learning.",
      "Practice mindfulness.",
      "Download wisdom from mistakes then delete them from memory.",
      "Embrace challenge.",
      "Mistakes are the ideal learning opportunities.",
      "Intelligence expands exponentially with effort.",
      "Learning is the tingling magic dust of the mind.",
      "Your mind is the most absorbent sponge of all knowledge.",
      "Can you teach it? If not, you haven't learned it yet.",
      "Let your name be known as synonymous with Learning.",
      "Learn by doing, failing, and doing it again better.",
      "It is impossible for a person to learn what he or she thinks they already know.",
      "With goal in mind, failure is but a stepping stone.",
      "Books are the training weights of the mind.",
      "Skillful pilots gain their reputation from storms and tempests.",
      "Learning takes patience and persistence. Even Einstein began with 1 + 1 = 2.",
      "Persistence solves any problem.",
      "Read something substantial at least half an hour every day.",
      "It's not intelligence or talent that solves most problems: It's persistence.",
      "Download lessons from mistakes then delete it from memory.",
      "An investment in knowledge pays the best interest.",
      "Stay hungry. Stay foolish.",
      "The greatest learners are not the smartest or most talented: They are the most persistent.",
      "Always be open to new information.",
      "Only the educated are free.",
      "Whoever sees himself as the sole judge of Truth will be shipwrecked by the laughter of the gods."
    ]
  }
];

   // Category.collection.remove({}, function(err) {
   //      console.log('collection removed')
   //      });

   // Category.collection.insertMany(data, function(err,r) {
   //  assert.equal(null, err);
   //  assert.equal(10, r.insertedCount);
   // });

module.exports = Category;