var mongoose = require('mongoose');
var assert = require('assert');
var bluebird = require('bluebird');
// var db = require('../index.js');

var categorySchema = new mongoose.Schema({
  name: String,
  description: String,
  mottoes: [String],
  beliefs: [String]
});

var Category = mongoose.model('Category', categorySchema);

var data = [
  {
    "name":"Spirituality",
    "description": "Religion, faith or belief in a higher power.",
    "mottoes":[
      "Faith. Hope. Never quit."
    ],
    "beliefs":[
      "Pray every morning.",
      "God helps those that help themselves.",
      "That which does not kill us only makes us stronger.",
      "Believe in yourself.",
      "The future is as bright as your faith.",
      "Faith is taking the first step even when you don't see the stairs.",
      "If God brings you to it, He will bring you through it.",
      "Understand that to achieve anything requires faith in yourself, hard work and determination.",
      "All things are possible to those who believe.",
      "Be faithful in small things because it is in them that your strength lies.",
      "Have faith in your abilities.",
      "We are twice armed if we fight with faith.",
      "I move not without Thy knowledge!",
      "Make love a priority in all your decisions.",
      "The world turns aside to let any man pass who knows where he is going.",
      "In great difficulty, you will argue with yourself that there is no way forward. But with God, nothing is impossible.",
      "Attach yourself to what is spiritually superior, regardless of what other people think or do.",
      "Fasting brings you closer to God.",
      "It's lack of faith that makes people afraid of meeting challenges.",
      "Let your Faith be bigger than your fear."
    ]
  },
  {
    "name":"Hope",
    "description": "Expectation and desire for a positive outcome.",
    "mottoes":[
      "Hope. Faith. Never quit.",
      "Strength  Wisdom  Courage"
    ],
    "beliefs":[
      "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
      "Learn from yesterday. Live for today. Hope for tomorrow.",
      "Ask yourself: Why? Why not? Why not me? Why not now?",
      "God helps those that help themselves.",
      "It is better to light a candle than to curse the darkness.",
      "The secret of change is to focus all your energy, not on fighting the old, but on building the new.",
      "Start where you are. Use what you have. Do what you can.",
      "There must be darkness for the dawn to come.",
      "Be willing to give up what you are to become what you will be.",
      "Out of suffering emerge the strongest souls.",
      "Find the light, faint though it may be, and never, ever stop moving toward it.",
      "The future is not some place we are going but one we are creating.",
      "The greater the difficulty, the more glory in surmounting it.",
      "It's not what happens to you, but how you react to it that matters.",
      "The pain you've been feeling can't compare to the joy that's coming.",
      "The past cannot be changed. The future is within your power.",
      "The past cannot be changed. The future is within reach.",
      "The future is filled with unknowable wonder.",
      "The best way to predict the future is to create it.",
      "When you're angry at a loved one, imagine waking up tomorrow without them.",
      "The future is as bright as your faith,",
      "It is not in the stars to hold our destiny but in ourselves.",
      "Tomorrow is an unknowable canvas. You wield the brush.",
      "It is difficulties that show what men are.",
      "Practice mindfulness and perform acts of kindness everyday.",
      "You are stronger than whatever you are facing.",
      "In times of adversity, just keep moving forward.",
      "We are here to laugh at the odds and live our lives so well that death will tremble to take us.",
      "Every adversity, failure and heartache carries with it the seed of an equal or greater benefit.",
      "You are neither your thoughts nor your emotions. Only the weak are subject to them.",
      "Above all, always and in every case, face your fear.",
      "The pain of today is the strength of tomorrow.",
      "Skillful pilots gain their reputation from storms and tempests.",
      "Do not let what you cannot do interfere with what you can do.",
      "Keep your face always toward the sunshine -- and shadows will fall behind you.",
      "Dismiss what insults your soul and your very flesh shall be a great poem.",
      "You must travel it by yourself. It is not far. It is within reach.",
      "In the middle of difficulty lies opportunity."
    ]
  },
  {
    "name":"Compassion & Empathy",
    "description": "Kindness and the ability to understand the feelings of another.",
    "mottoes":[
      "Kindness Matters"
    ],
    "beliefs":[
      "Always be kind",
      "Be kind. Everyone you meet is fighting a battle.",
      "Forgiveness is the attribute of the strong.",
      "See people from where they stand, not from where you stand.",
      "A word of encouragement during a failure is worth more than an hour of praise.",
      "Practice mindfulness and perform acts of kindness everyday.",
      "There is something to be learned from everyone.",
      "Everyone you meet is either a blessing or a lesson.",
      "Take nothing personally. Nothing others do is because of you.",
      "Before you speak, answer these: Is it true? Is it necessary? Is it kind?",
      "Be kind. Impose your will forcefully upon those who are not.",
      "One kind word can warm three winter months.",
      "Life isn't worth living unless it is lived for someone else.",
      "Preparation is the key to remaining calm under pressure.",
      "If someone loves you and hurts you, chances are they're in pain.",
      "Find joy in the accomplishments of others.",
      "Do unto others as you would have them do unto you.",
      "You are neither your thoughts nor your emotions. Only the sad are slaves to them.",
      "Make love a priority in all your decisions.",
      "Apologize when you've wronged. Do not withhold forgiveness.",
      "When you meet people, show appreciation then genuine curiosity. Everyone has something interesting.",
      "Listening is the beginning of understanding.",
      "Consider the rights of others before your own feelings.",
      "People are flawed. So are you. Forgive them.",
      "Everyone has at least one thing interesting about them. Find it.",
      "Any person capable of angering you becomes your master.",
      "Consider the feelings of others.",
      "It's not what happens to you, but how you react to it that matters.",
      "It's easy to see the splinter in someone else's eye and miss the log in your own.",
      "Be curious, not judgmental.",
      "I do not ask the wounded person how he feels, I myself become the wounded person.",
      "Treat others as you would treat yourself.",
      "When someone is feeling down, paint for them a compelling future.",
      "Compliment others.",
      "Ask yourself how you would feel in their shoes.",
      "Whoever sees himself as the judge of Truth and Knowledge will be shipwrecked by the laughter of the gods."
    ]
  },
  {
    "name":"Hard Work/Goals",
    "description": "Habitually setting goals and being persistent in achieving them.",
    "mottoes":[
      "Diligence  Resilience  Integrity",
      "Excellence Through Effort",
      "Choose To Strive",
      "Always Moving Forward"
    ],
    "beliefs":[
      "Feeling bad? WORK yourself better.",
      "Be quick, but don't hurry.",
      "Well done is better than well said.",
      "Never leave till tomorrow what can be done today.",
      "'I didn't fail. I just found 99 ways to do it wrong.'",
      "Excellence is not an act but a habit.",
      "When learning a new skill, prioritize excellence over speed. The speed will come.",
      "Victory happens when preparation meets opportunity.",
      "Adjust or accept. Do not whine.",
      "The person who removes a mountain begins by carrying away small stones.",
      "Every night before bed, write down three goals for tomorrow.",
      "Write down each goal, tell it to friends and loved ones, then make it happen.",
      "Keep your hands out of your pockets. There is always something to do.",
      "Wake an hour earlier than everyone else to pray, learn and exercise.",
      "Tame your pain.",
      "Better a little which is well done than a great deal done imperfectly.",
      "Procrastination is for lesser souls.",
      "Do what you can with what you have, where you are.",
      "He that is good at making excuses is seldom good at anything else.",
      "Working through fatigue strengthens the soul.",
      "A day without Goals is a day without water for the soul.",
      "Procrastination, excuses and complaints are for lesser souls.",
      "Let your name be known as synonymous with Diligence.",
      "Once a goal in mind is made, the Finished Path is always stayed.",
      "Pleasure in the job puts perfection in the work.",
      "Find or create value then do it better than everyone else.",
      "Download wisdom from mistakes then delete them from memory.",
      "Visualize accomplishment then anticipate and strategize probable challenges.",
      "The only way through suffering is straight through it.",
      "Strive for excellence in everything you do.",
      "You may delay, but time will not.",
      "Early to bed and early to rise makes a man healthy, wealthy and wise.",
      "A man who dares to waste one hour of time has not discovered the value of life.",
      "Whining and excuses are for lesser souls.",
      "The world owes you nothing. Earn everything.",
      "Do not let what you cannot do interfere with what you can do.",
      "Excuses are for lesser souls.",
      "What matters in life are results. No one cares about your excuses.",
      "Full effort is full victory.",
      "Make your bed first thing every morning.",
      "If you don't have time to do it right, when will you have time to do it over?",
      "The world belongs to the energetic.",
      "There are no shortcuts to anyplace worth going.",
      "Fill the unforgiving minute with sixty seconds of distance running.",
      "Hard work can help you accomplish anything.",
      "Wake up two hours early to read, work or learn something new.",
      "Pain is weakness leaving the body.",
      "Hard Work brings love and acceptance.",
      "Good things come to those who work hard and never give up.",
      "Always make a total effort, even when the odds are against you.",
      "Nothing of real value comes easily.",
      "Luck is real. The harder you work, the more you have.",
      "Without labor, nothing prospers.",
      "Want something? There are no shortcuts to an achievement of real value. Go earn it."
    ]
  },
  {
    "name":"Perseverance",
    "description": "Moving toward completion of a goal despite difficulty or delay.",
    "mottoes":[
      "Hope. Faith. Never quit.",
      "Decide. Commit. Succeed.",
      "Integrity  Honor  Courage.",
      "Strength  Endurance  Triumph",
      "Embracing Challenge",
      "Strength  Wisdom  Courage",
      "We Step Toward Challenges"
    ],
    "beliefs":[
      "Never, ever quit",
      "Suffer now and live the rest of your life like a champion.",
      "Energy and persistence conquer all things.",
      "The temptation to quit is greatest just before you are about to succeed.",
      "On the plains of hesitation lie the blackened bones of countless millions who, at the dawn of victory sat down to rest, and resting, died.",
      "Pain is temporary. Quitting is forever.",
      "Fear brings more pain than the pain it fears.",
      "Never give up, no matter how impossible the situation looks. That's how legends are born.",
      "It's at the borders of pain and suffering that men are separated from boys.",
      "Souls are awakened out of suffering. The greatest souls endure many scars.",
      "Strength and growth come only through continuous effort and struggle.",
      "Above all, face your fear.",
      "A person who never made a mistake never tried anything new.",
      "Failure is not falling down but refusing to get back up.",
      "The pain of today is the strength of tomorrow.",
      "Out of suffering emerge the strongest souls. The most massive characters are seared with scars.",
      "Working through fatigue strengthens the soul.",
      "Working through fatigue brings us closer to God.",
      "Adjust or accept. Do not whine.",
      "No matter how you feel, get up, show up and never give up.",
      "Every adversity, failure and heartache carries with it the seed of an equal or greater benefit.",
      "Embody grit and toughness.",
      "Let your name be known as synonymous with Perseverance.",
      "You are neither your thoughts nor your emotions. Only the weak are subject to them.",
      "Wear failed attempts as badges of honor.",
      "Seek and embrace challenge - it forges your mettle.",
      "Seek and embrace challenge - it is the most certain path to strength.",
      "Vanquish your subservience to pain.",
      "Strength = Pain Endured",
      "Pain is inevitable. Suffering is optional.",
      "Nothing worth having ever comes easily.",
      "Pain is a divine rite of passage through which you are reborn as a being of strength and purpose.",
      "Endure and persist and the world will open itself to you.",
      "Hold true to your aspirations no matter what is going on around you.",
      "Excuses are for lesser souls.",
      "Poor is the man who is a slave to pain.",
      "Quitting is for lesser souls.",
      "Embrace the pain. Enjoy the gain.",
      "Skillful pilots gain their reputation from storms and tempests.",
      "The greater the difficulty, the more glory in surmounting it.",
      "It's not what happens to you, but how you react to it that matters.",
      "Failure is not fatal, but failure to change might be.",
      "Courage and perseverance are magical talismen, before which difficulties and obstacles crumble.",
      "Failing and losing aren't the same. Quitting is losing. Failing brings you closer to your goal.",
      "There are no dumb questions. Only dumb people that don't ask them.",
      "Failure brings you one step closer to your goal.",
      "Work. Fail. Repeat.",
      "There are no mistakes in service of a goal. There are only lessons learned.",
      "Never make excuses.",
      "In the middle of difficulty lies opportunity.",
      "Failure brings you one step closer to your goal.",
      "Pain is weakness leaving the body."
    ]
  },
  {
    "name":"Wisdom",
    "description": "The quality of using good judgement in decisions.",
    "mottoes":[
      "Strength  Wisdom  Courage"
    ],
    "beliefs":[
      "The doorstep to the Temple of Wisdom is knowledge of our own ignorance.",
      "When in doubt, use discretion.",
      "Forget what hurt you but never forget what it taught you.",
      "Sometimes you win. Sometimes you learn.",
      "He who is not courageous enough to take risks will accomplish nothing in life.",
      "Wisdom begins in wonder.",
      "Change in all things is sweet.",
      "You will never do anything in this world without courage. It is the greatest quality of mind next to honor.",
      "Learn from yesterday. Live for today. Hope for tomorrow.",
      "Courage is knowing what not to fear.",
      "An ounce of prevention is worth a pound of cure.",
      "Thinking - the talking of the soul with itself.",
      "Wise men speak because they have something to say; Fools because they have to say something.",
      "When the winds of change blow, some build walls. Smart people build windmills.",
      "To find yourself, think for yourself.",
      "The first and greatest victory is to conquer yourself. Not doing so is of all things most shameful and vile.",
      "True wisdom comes to each of us when we realize how little we understand about life, ourselves and the world.",
      "Do not answer a question until you understand why it was asked.",
      "Tell stories of times you were wrong and the lessons learned.",
      "Regardless of circumstances, always evaluate new information. Always.",
      "Priorities: Physically fit, emotionally stable and spiritually sound.",
      "Practice the art of predicting the eventuality of events as they are happening.",
      "Adjust or accept. Do not whine.",
      "Men acquire a particular quality by consistently acting in a particular way.",
      "Only idiots make the same mistake twice.",
      "Energy and persistence conquer all things.",
      "The only true wisdom is in knowing you know nothing.",
      "Think before you act. Something done in an instant can give you heartache for life.",
      "Evaluate the probable effects of what you want to say. Then and only then, speak.",
      "Change what you can, accept what you can't and remove yourself from the unacceptable.",
      "In times of pleasurable temptation, focus your thoughts on a different pleasure.",
      "Let your word become known as unimpeachable.",
      "Practice holding opposing ideas in your mind simultaneously. The world is rarely black or white.",
      "Fix Reason firmly in her seat and call to her tribunal every fact, every opinion.",
      "He that is good at making excuses is seldom good at anything else.",
      "Poor is the man who is slave to his emotions.",
      "Inside each of us are two fighting wolves, Good and Bad. Which one wins? The one you feed.",
      "Worrying is as effective as trying to solve an algebra problem by chewing bubble gum.",
      "If you are patient in one moment of anger, you will escape a hundred days of sorrow.",
      "Visualize accomplishment then anticipate and strategize probable challenges.",
      "For there is nothing good or bad, but thinking makes it so.",
      "Do unto others as you would have them do unto you.",
      "You are neither your thoughts nor your emotions. Only the weak are subject to them.",
      "Always face your fears.",
      "The fishermen know the sea is dangerous and the storm terrible. But they have never found these reasons sufficient for staying ashore.",
      "Preparation is the key to remaining calm under pressure.",
      "Always be open to new information.",
      "Do not deny your emotions. Master them.",
      "Download lessons from mistakes then delete them from memory.",
      "Don't let yourself be controlled by people, money or past experiences.",
      "Seek feedback and be open to criticism. They are the paths to excellence.",
      "Control thy passions lest they take vengeance on thee.",
      "Any person capable of angering you becomes your master.",
      "It is the act of an ill-constructed man to blame others for his own bad condition.",
      "Success is never final; failure is never fatal. It's courage that counts.",
      "If you don't have time to do it right the first time, when will you have time to do it over?",
      "Trust your gut to point in the right direction. Then use logic and reason to make the decision.",
      "Apologize when you've wronged. Do not withhold forgiveness.",
      "Choose your words wisely, embrace every moment and never waste time.",
      "Strive for excellence in everything you do.",
      "Attend to nothing except reason in everything you encounter.",
      "Attach yourself to what is spiritually superior, regardless of what other people think or do.",
      "It's not what happens to you, but how you react to it that matters.",
      "Never make excuses.",
      "First learn the meaning of what you will say. Then speak.",
      "Exercise and practice mindfulness daily.",
      "Do not let what you cannot do interfere with what you can do."
    ]
  },
  {
    "name":"Knowledge of Money",
    "description": "The fundamentals of money and using good judgement in financial decisions.",
    "mottoes":[
      "Strength  Integrity  Wealth"
    ],
    "beliefs":[
      "Invest one-fourth of everything you earn.",
      "Beware of little expenses. A small leak will sink a great ship.",
      "To succeed, jump as quickly at opportunities as you do at conclusions.",
      "Learn the rules of the game. Then play better than anyone else.",
      "Always pay yourself first by investing one-fourth of your earnings before doing anything else.",
      "Never spend on the unnecessary what you haven't already earned.",
      "Smart people spend less than they earn and invest the rest.",
      "Money is a tool, not a result.",
      "A dollar invested is a dollar earned.",
      "The greatest wealth is to live content with little.",
      "Never underestimate the value of money.",
      "The only real security a man will have in this world is a reserve of knowledge, experience and ability.",
      "Practice the art of predicting the eventuality of events as they are happening.",
      "Adjust or accept. Do not whine.",
      "Find or create something of value then do it better than anyone else.",
      "Never spend money before you have it.",
      "Money is just a way to keep score. The real excitement is playing the game.",
      "Attend to nothing except reason in everything you encounter.",
      "Money is a tool for making more money.",
      "A wise man should have money in his head, but not in his heart.",
      "Do what you love and the money will follow.",
      "In all matters of money, take nothing personally but remain vigilant - everyone is self-interested.",
      "Always be open to new information.",
      "The smartest people invest more than they spend on the unnecessary.",
      "Always pay yourself first.",
      "Remain grounded. Great opportunity can be found when others believe the sky is falling.",
      "Always know your exact net worth.",
      "Find or create something you love doing that has marketable value.",
      "Live on half your pre-tax income.",
      "Focus your mind on Prosperity, not debt.",
      "Value = Useful",
      "Money grows on the Tree of Persistence.",
      "For all significant financial moves, sleep on it.",
      "Money = Freedom",
      "Separate money from emotion.",
      "Loopholes are hidden everywhere. Find them.",
      "Keep a ledger. That which is measured, improves."
    ]
  },
  {
    "name":"Integrity",
    "description": "The quality of being honest and having strong moral principles.",
    "mottoes":[
      "Integrity  Strength  Courage"
    ],
    "beliefs":[
      "It's not our thoughts or emotions that define us. It is our actions.",
      "We are responsible for our actions, no matter how we feel.",
      "Honesty is the best policy.",
      "Good actions give strength to ourselves and inspire good actions in others.",
      "It is not living that matters, but living rightly.",
      "Truth is the beginning of every good to the gods and of every good to man.",
      "The only correct actions are those that demand no explanation and no apology.",
      "Courage + Integrity = Character",
      "The first and greatest victory is to conquer yourself. Not doing so is of all things most shameful and vile.",
      "False words are not only evil in themselves, but they infect the soul with evil.",
      "Never 'for the sake of peace and quiet' deny your own experience or convictions.",
      "It takes less time to do a thing right than to explain why you did it wrong.",
      "Men acquire a particular quality by constantly acting in a particular way.",
      "To know what is right and not do it is the worst cowardice.",
      "Master your emotions.",
      "Truthfulness is the main element of character.",
      "Integrity is the essence of everything successful.",
      "Relentlessly pursue honesty at all times.",
      "To thine own self be true, and it must follow, as the night the day, thou canst not then be false to any man.",
      "Refuse to to do or say anything that damages your self-respect.",
      "Credibility can only be built over time from the history of your words and actions.",
      "The true perfection of man lies not in what man has, but in what man is.",
      "Whoever is careless with the truth in small matters cannot be trusted with important matters.",
      "Power is actualized only when word and deed have not parted company.",
      "Real integrity is doing the right thing, knowing that nobody's going to know whether you did it or not.",
      "Do what you say you will do.",
      "You are already of consequence in the world if you are known as a man of strict integrity.",
      "If you tell the truth, you don't have to remember anything.",
      "Keep true, never be ashamed of doing right, decide on what you think is right and stick to it.",
      "Never make excuses.",
      "First learn the meaning of what you will say. Then speak.",
      "Choose your words wisely.",
      "Keep your promises.",
      "If you don't have time to do it right the first time, when will you have time to do it over?",
      "It is the act of an ill-constructed man to blame others for his own bad condition.",
      "Let your name be known as synonymous with Integrity.",
      "Evaluate the probable effects of what you want to say. Then and only then, speak.",
      "Your word is your bond.",
      "Always tell the truth.",
      "Truth alone endures. All the rest are swept away within the tide of time.",
      "Adjust or accept. Do not whine.",
      "Weakness of attitude becomes weakness of character.",
      "If you wish to know a man, ignore his words and observe his actions."

    ]
  },
  {
    "name":"Self-Discipline",
    "description":"The ability to delay gratification.",
    "mottoes":[
      "Hope. Faith. Never quit."
    ],
    "beliefs":[
      "In times of temptation, reflect on what you're grateful for.",
      "Do something everyday that scares you.",
      "Early to bed and early to rise makes a man healthy, wealthy and wise.",
      "The person who removes a mountain begins by carrying away small stones.",
      "Don't rest when you're tired. Rest when you're done.",
      "Control thy passions lest they take vengeance on thee.",
      "The greatest wealth is to live content with little.",
      "An ounce of prevention is worth a pound of cure.",
      "Out of suffering emerge the strongest souls. The most massive characters are seared with scars.",
      "The pain of today is the strength of tomorrow.",
      "Preparation is the key to remaining calm under pressure.",
      "Mindfulness meditation is exercise for the mind. Do it every day.",
      "Exercise and practice mindfulness every day.",
      "You are neither your thoughts nor your emotions. Only the weak are subject to them.",
      "No man is free who is not a master of himself.",
      "Capitulation is for lesser souls.",
      "He who angers you conquers you.",
      "Master mindfulness.",
      "Meticulously keep a food diary or a financial ledger.",
      "Begin every day by making your bed with excellence then meditating for ten minutes.",
      "With large goals, break them down into manageable chunks. Then pick a chunk and get to it.",
      "Meditation is like push-ups for your mind. Do it every day.",
      "Occasional fasting strengthens the will and the spirit.",
      "Poor is the man ruled by his emotions.",
      "For there is nothing good or bad, but thinking makes it so.",
      "Making your bed perfectly is the first thing you do every day of your life.",
      "Do not judge the day by the harvest you reap but by the seeds you plant.",
      "Remain vigilant: Your progress can be wrecked or preserved by a single day and a single event.",
      "Resolve to live as a grown-up, and make whatever you think best a law you never set aside.",
      "You are not your thoughts. You are not your emotions. You are your actions and only until you take them.",
      "Decisions against our betters selves offend the soul.",
      "Attach yourself to what is spiritually superior, regardless of what other people think or do.",
      "Begin everyday by counting your blessings.",
      "It's not what happens to you, but how you react to it that matters.",
      "When faced with temptation, occupy your mind with prayer, distraction or tell yourself you'll do it later.",
      "Fiercely guard your environment against temptation. When it's unavoidable, tell yourself you'll do it later.",
      "Forgive yourself, make corrections, redouble your efforts and move forward."
    ]
  },
  {
    "name":"Happiness",
    "description": "Helping others, having close relationships and doing something productive you enjoy.",
    "mottoes":[
      "Enjoying Every Moment",
      "Veni  Vidi  Amavi"
    ],
    "beliefs":[
      "Only fools worry about things beyond their control.",
      "Be yourself. Everyone else is already taken.",
      "Happiness lies in the joy of achievement, in the thrill of creative effort.",
      "Try something new. Enjoy the fun of failure.",
      "I am satisfied: I see, dance, laugh and sing.",
      "Wherever you are, be there totally.",
      "Make your needs known.",
      "The Constitution only gives people the right to pursue happiness. You have to catch it yourself.",
      "Be at war with your vices, at peace with your neighbors and let every new year find you a better person.",
      "Forget what hurt you but never forget what it taught you.",
      "The greatest wealth is to live content with little.",
      "Love is the joy of the good, the wonder of the wise and the amazement of the Gods.",
      "Always be growing. Always.",
      "Never stop growing.",
      "Don't cry because it's over. Smile because it happened.",
      "The minute you stop growing is the same minute you start dying.",
      "Practice holding opposing ideas in your mind simultaneously. The world is rarely black or white.",
      "Never outgrow play.",
      "Any person capable of angering you becomes your master.",
      "Become fluent in the five love languages.",
      "Regardless of circumstances, always evaluate new information. Always.",
      "When you meet people, show appreciation then genuine curiosity. Everyone has something interesting.",
      "Capture every opportunity by practicing the art of interpreting situations as they happen.",
      "Happiness is when what you think, what you say and what you do are in harmony.",
      "Enjoy it while it's here. Let go when it leaves.",
      "Our biggest regrets are often opportunities we miss because of fear.",
      "Download wisdom from mistakes then delete them from memory.",
      "Let insults roll off your back like water rolls off feathers.",
      "Adjust or accept. Do not whine.",
      "Worrying is as effective as trying to solve an algebra problem by chewing bubble gum.",
      "Practice mindfulness and perform acts of kindness everyday.",
      "Find joy in the accomplishments of others.",
      "For there is nothing good or bad, but thinking makes it so.",
      "Do unto others as you would have them do unto you.",
      "You are neither your thoughts nor your emotions. Do not be ruled by them.",
      "Apologize when you've wronged. Do not withhold forgiveness.",
      "Be true to yourself.",
      "Embrace change.",
      "Procrastination, excuses and complaints are for lesser souls.",
      "Consider your mortality.",
      "This day, like any day, could be your last. It's easy to forget that. So don't.",
      "Don't take yourself too seriously. Life is more farce than drama.",
      "We are here to laugh at the odds and live our lives so well that death will tremble to take us.",
      "Make love a priority in all your decisions.",
      "Covet not many things and you will obtain.",
      "Any person capable of angering you becomes your master.",
      "He who laughs at himself never runs out of things to laugh at.",
      "Don't seek to have events happen as you wish, but wish them to happen as they do.",
      "Begin everyday by counting your blessings.",
      "Find three hobbies you love: One to make money, one to stay in shape and one to be creative.",
      "Don't let yourself be controlled by people, money or past experiences.",
      "Seek not the good in external things; seek it in yourself.",
      "Wealth consists not in having great possessions, but in having few wants.",
      "Live so that your happiness depends as little as possible upon external things.",
      "First say to yourself what you would be. Then do what you have to do.",
      "Most friends come and go, but for a precious few, work hard to bridge the inevitable gaps in geography and lifestyle.",
      "Cease worrying about things which are beyond the power of our will.",
      "Do not let what you cannot do interfere with what you can do.",
      "You miss 100% of the shots you don't take.",
      "Above all, face your fears.",
      "Commit yourself everyday to have the heart of a lion, the skin of a rhino and the soul of an angel.",
      "Find someone to love, something to do and something to hope for.",
      "Choose your words wisely, embrace every moment and never waste time.",
      "It's better to be a failure at something you love than a success at something you hate.",
      "The greatest mistake you can make in life is to continually be afraid you will make one.",
      "Pick one and become excellent: Dance, sing or play an instrument.",
      "The wise do not grieve for which they have not, but rejoices for what they have.",
      "It's not what happens to you, but how you react to it that matters.",
      "At least in part, accept responsibility for everything that happens to you.",
      "Keep company with only those that uplift you, whose presence calls forth your best."

    ]
  },
  {
    "name":"Creativity",
    "description":"The ability to generate original ideas.",
    "mottoes":[
      "Different is Magnificent"
    ],
    "beliefs":[
      "Logic will get you from A to B. Imagination will take you Anywhere.",
      "To live a creative life we must lose our fear of being wrong.",
      "Make yourself sheep and the wolves will eat you.",
      "There is no great genius without a mixture of madness.",
      "Creativity is just connecting things we know in a different way.",
      "Question everything you hear and see.",
      "Embrace change.",
      "Ask yourself: Why? Why not? Why not me? Why not now?",
      "Rebellion against common thought is obedience to God.",
      "A person who never made a mistake never tried anything new.",
      "Simplicity is the ultimate sophistication.",
      "Learn how to see. Realize that everything connects to everything else.",
      "Any product that needs a manual to work is already broken.",
      "If things are not failing, you're not innovating enough.",
      "Solicit negative feedback from friends. They're the ones most likely to be honest.",
      "Constantly think about how you could be doing things better. Keep questioning yourself.",
      "Establish a feedback loop where you're constantly thinking about what you've done and how you can do it better.",
      "See yourself not as a generator of ideas but as a conduit connecting your world to the Infinite.",
      "Do something everyday that scares you.",
      "Regardless of circumstances, always evaluate new information. Always.",
      "Trust your instincts.",
      "Stay in divine preparation for receiving.",
      "At least once a day, allow yourself to think and dream in solitude.",
      "Creating something new is accomplished not by the intellect but by the play instinct.",
      "Spend more time thinking about the problem than thinking up solutions.",
      "Download wisdom from mistakes then delete them from memory.",
      "Be true to yourself.",
      "Embrace duality of thought.",
      "Practice holding opposing ideas in your mind simultaneously. The world is rarely black or white.",
      "Trust your gut, value fantasy, be open to new experiences and play with problems.",
      "Wear failed attempts as badges of honor.",
      "Anyone who has never made a mistake has never tried anything new.",
      "This is not a sentence.",
      "Let insults roll off your back like water off feathers.",
      "The important thing is to not stop questioning.",
      "Above all, face your fears.",
      "Out of clutter, find simplicity.",
      "Never outgrow play.",
      "No one is remembered for being normal.",
      "If you cannot find a way, make one.",
      "Only those who attempt the absurd achieve the impossible.",
      "The most beautiful experience we can have is the mysterious.",
      "Don't take yourself too seriously.",
      "Consider your mortality.",
      "Seek feedback and be open to criticism. They are guideposts to improvement.",
      "Not doing something out of fear of looking stupid is more stupid than anything you can possibly do.",
      "Do not let what you cannot do interfere with what you can do.",
      "You miss 100% of the shots you don't take.",
      "The greatest mistake you can make in life is to continually be afraid you will make one.",
      "Creativity is intelligence having fun.",
      "Life is a great big canvas. Throw all the paint you can on it.",
      "Some see things and ask why. Dream things that never were and ask 'Why not?'",
      "It's good to remember and easy to forget: You don't have to do what everyone else is doing.",
      "Revel in your difference.",
      "Almost anything is possible.",
      "If you're going to fail, fail with 100% effort.",
      "Life is absurd. Be comfortable with appearing foolish.",
      "Sometimes it's wonderful to be silly.",
      "Make mistakes, look like an idiot, then try again - without flinching.",
      "Try something new. Enjoy the fun of failure.",
      "Different is Magnificent.",
      "Each day is a gift. Honor yourself and your family by never taking it for granted.",
      "Observe the human comedy.",
      "Be yourself. Everyone else is already taken.",
      "Stay hungry. Stay foolish."
    ]
  },
  {
    "name":"Learning",
    "description":"Gaining knowledge or skills.",
    "mottoes":[
      "Always Learning"
    ],
    "beliefs":[
      "Always be learning.",
      "Practice mindfulness.",
      "An investment in knowledge pays the best interest.",
      "The educated differ from the uneducated as much as the living from the dead.",
      "The more you read, the more things you'll know. The more you learn, the more places you'll go.",
      "The noblest pleasure is the joy of understanding.",
      "Wisdom begins in wonder.",
      "Download wisdom from mistakes then delete them from memory.",
      "Embrace challenge.",
      "Mistakes are the ideal learning opportunities.",
      "Intelligence expands exponentially with effort.",
      "Learning is the tingling magic dust of the mind.",
      "Your mind is the most absorbent sponge of knowledge.",
      "Can you teach it? If not, you haven't learned it yet.",
      "Let your name be known as synonymous with Learning.",
      "Learn by doing, failing, and doing it again better.",
      "It is impossible for a person to learn what he or she thinks they already know.",
      "With goal in mind, failure is but a stepping stone.",
      "When you meet people, show appreciation then genuine curiosity. Almost everyone has something you can learn.",
      "Books are the training weights of the mind.",
      "Skillful pilots gain their reputation from storms and tempests.",
      "Learning takes patience and persistence. Even Einstein began with 1 + 1 = 2.",
      "Persistence solves any problem.",
      "Read fiction or something educational at least an hour every day.",
      "It's not intelligence or talent that solves most problems: It's persistence.",
      "Download lessons from mistakes then delete them from memory.",
      "An investment in knowledge pays the best interest.",
      "Stay hungry. Stay foolish.",
      "The greatest learners are not the smartest or most talented: They are the most persistent.",
      "Regardless of circumstances, always evaluate new information. Always.",
      "Only the educated are free.",
      "Whoever sees himself as the sole judge of Truth will be shipwrecked by the laughter of the gods."
    ]
  },
  {
    "name":"Human Nature",
    "description":"Understanding people.",
    "mottoes":[
      "To Err is Human"
    ],
    "beliefs":[
      "To err is human, to forgive divine.",
      "Three may keep a secret if two of them are dead.",
      "All grown-ups were once children, but only few of them remember it.",
      "The mass of men lead lives of quiet desperation.",
      "Where there is shouting, there is no true knowledge.",
      "The greatest deception men suffer is from their own opinions.",
      "Everyone lies. Everyone. Pay more attention to one's actions than their words.",
      "Most people you see every day are struggling through something. Be kind.",
      "People will give up anything for what they want most.",
      "Everyone's greatest fear is their own death.",
      "Man is by nature a political animal.",
      "Discretion is the better part of valor.",
      "How to Love: Treat others as what they are capable of becoming. Laugh and forgive them on the way.",
      "How to Find Love: Discover which of the five love languages they speak. Become fluent.",
      "Men are swayed more by fear than reverence.",
      "You are today where your thoughts have brought you. Tomorrow, you'll be where they take you. Thoughts are choices.",
      "It's not easy to do, but most people love to laugh at themselves.",
      "Want women? Learn to Listen like a Boss.",
      "Circumstances do not make the man. They reveal him.",
      "Ask yourself: Why? Why not? Why not me? Why not now?",
      "Most people would rather give than get affection.",
      "Power corrupts. Absolute power corrupts absolutely.",
      "Attack where they are unprepared. Appear where and when you are not expected.",
      "In battle, deception is a powerful ally.",
      "In battle, strike your first blow with devastating force.",
      "Human nature flows from three main sources: Desire, emotion and knowledge.",
      "We can easily forgive a child who is afraid of the dark. The real tragedy is when men are afraid of the light.",
      "The secret of change is to focus all your energy, not on fighting the old, but on building the new.",
      "Those who are hardest to love often need it the most.",
      "You can discover more about a person in an hour of play than in a year of conversation.",
      "From the deepest desires often comes the deadliest hate.",
      "Never underestimate the power of denial.",
      "There are three things extremely hard: Steel, a diamond and to know oneself.",
      "Give someone a mask and they'll show you their true face.",
      "Everyone is a moon and has a dark side which he never shows to anybody.",
      "Kindness is the language which the deaf can hear and the blind can see.",
      "The majority of people have little awareness of the difference between thoughts and emotions.",
      "If you wish to know a man, ignore his words and observe his actions.",
      "If a loved one hurts you, consider they may be in pain themselves and could use a helping hand.",
      "Take nothing personally. Nothing others do is because of you.",      
      "Be warm and open to others but remain wary: Most are self-interested and many will take from you what they can.",
      "Most people want more than anything to feel connected to someone or to something greater than themselves."
    ]
  },
  {
    "name":"Privacy & Technology",
    "description":"Knowledge and skills helpful to advances in the accessibility of information.",
    "mottoes":[
      ""
    ],
    "beliefs":[
      "Always think twice before posting.",
      "Whatever is begun in anger ends in shame.",
      "All sent messages are documented forever. Think twice before hitting 'Send'.",
      "One angry comment left unposted can save a hundred versions of sorrow.",
      "Never post when you're angry.",
      "When anger arises, think of the consequences.",
      "It is impossible for a person to learn what he or she thinks they already know.",
      "Texting while driving is something idiots do.",
      "When searching for information, bookmark alternate paths until you find it. Then, and only then, explore."


    ]
  }


];

   // Category.collection.remove({}, function(err) {
   //      console.log('collection removed')
   //      });

   // Category.collection.insertMany(data, function(err,r) {
   //  assert.equal(null, err);
   //  assert.equal(14, r.insertedCount);
   // });

module.exports = Category;